const dotenv = require('dotenv')
dotenv.config()
const express = require('express')
const cors = require('cors')
const app = express()
const users = require('./routers/userRouter')
const kategories = require('./routers/kategoryRouter')
const products = require('./routers/productRouter')
const error = require('./routers/errorRouter')
const ErrorHandlers = require('./middlewares/errorHandlers')
const MiddleWareFunctions = require('./middlewares/logMiddleware')
const { loggedIn } = require('./middlewares/authMiddlewares')
const bodyParser = require('body-parser')
app.use(cors())
app.use(bodyParser.json())
app.use(bodyParser.urlencoded({ extended: false }))
app.use('/Yad2/users', users)
app.use(loggedIn)
app.use(ErrorHandlers.checkBody)
app.use(MiddleWareFunctions)
app.use('/Yad2/kategories', kategories)
app.use('/Yad2/products', products)
app.use('/*', error)
const port = process.env.PORT || 3000
app.listen(port, () => {
  console.log(`listening on http://localhost:${port}`)
})
